import json

new_en = {
    "choose_option_menu": "\nChoose an option:",
    "download_oc_fail_log": "Failed to download OpenCore. Check the log for more details.",
    "oc_pre_release_prompt": "Enter build type (RELEASE/DEBUG) for the pre-release version: ",
    "oc_pre_release_success": "OpenCore (pre-release) successfully updated!",
    "cleaning_temp_files": "Cleaning up temporary files...",
    "cleaning_done": "Cleanup finished.",
    "detecting_fat32_efi": "FAT32/EFI partitions detected (HDs and thumb drives):",
    "no_fat32_efi_found": "No FAT32 or EFI partition found on the system.",
    "unknown_disk": "Unknown Disk",
    "downloading_oc_version": "Downloading OpenCore version {build_type}...",
    "latest_pre_release_not_found": "Error: Could not find an OpenCore pre-release version.",
    "latest_pre_release_link_error": "Error: Could not retrieve the link for pre-release {build_type}.",
    "pre_release_link_found": "OpenCore pre-release download link {build_type} found: {oc_url}",
    "api_link_found": "Download link via API found: {oc_url}",
    "api_rate_limit_warning": "Warning: GitHub API rate limit (403 Rate Limit) exceeded.",
    "smart_fallback_init": "Starting Smart Fallback mechanism for download...",
    "smart_fallback_link": "Link generated by Smart Fallback: {oc_url}",
    "smart_fallback_error": "Critical error: Fallback failed and the official API is blocked.",
    "smart_fallback_unsupported_pre": "Critical error: No Smart Fallback available for pre-release versions on Rate Limit. Try again later.",
    "checksum_error_skip": "Could not retrieve SHA-256 checksum. Verification skipped. Error: {e}",
    "size_not_specified": "Size not specified by server, downloading...",
    "download_size_mismatch": "Error: Download size mismatch. File might be corrupted.",
    "checksum_fatal_error": "Fatal Error: SHA-256 Checksum from downloaded file ({downloaded_checksum}) does not match expected ({expected_checksum}). File might be compromised!",
    "checksum_verified_super": "SHA-256 Checksum verified successfully.",
    "oc_download_extract_success": "OpenCore version {build_type} downloaded and extracted 100% securely.",
    "chk_version_api_err": "Failed to check version via API (possibly Rate Limit). Attempting Smart Fallback...",
    "smart_fallback_active": "Smart Fallback Active: Version {tag} retrieved successfully!",
    "smart_fallback_failed": "Smart Fallback also failed: {fallback_e}",
    "dependencies_check": "Checking dependencies...",
    "dependency_not_found": "Error: Dependency '{cmd}' not found.",
    "python3_needed": "Python 3 is required for the script. Install it via Homebrew with 'brew install python3'.",
    "dependencies_success": "All dependencies are available.",
    "invalid_option": "Invalid option. Please try again.",
    "backup_limit_deleted": "Deleted older backup to maintain rotation limit: {folder}",
    "y_n_prompt": "(y/n)",
    "safe_delete_prompt": "Are you absolutely sure you want to permanently delete these drivers? (y/n): ",
    "drivers_kept": "Drivers were kept safely in EFI.",
    "drivers_unused_removed": "Unused drivers removed from EFI."
}

new_pt = {
    "choose_option_menu": "\nEscolha uma opção:",
    "download_oc_fail_log": "Falha ao baixar o OpenCore. Verifique o log para mais detalhes.",
    "oc_pre_release_prompt": "Digite o tipo de build (RELEASE/DEBUG) para a versão pré-lançamento: ",
    "oc_pre_release_success": "OpenCore (pré-lançamento) atualizado com sucesso!",
    "cleaning_temp_files": "Limpando arquivos temporários...",
    "cleaning_done": "Limpeza concluída.",
    "detecting_fat32_efi": "Partições FAT32/EFI detectadas (HDs e Pendrives):",
    "no_fat32_efi_found": "Nenhuma partição FAT32 ou arquivo EFI foi encontrada no sistema.",
    "unknown_disk": "Disco Desconhecido",
    "downloading_oc_version": "Baixando OpenCore versão {build_type}...",
    "latest_pre_release_not_found": "Erro: Não foi possível encontrar uma versão pré-lançamento do OpenCore.",
    "latest_pre_release_link_error": "Erro: Não foi possível obter o link da versão pré-lançamento {build_type}.",
    "pre_release_link_found": "Link de download do OpenCore pré-lançamento {build_type} encontrado: {oc_url}",
    "api_link_found": "Link de download via API encontrado: {oc_url}",
    "api_rate_limit_warning": "Aviso: Limite de requisições da API do GitHub (403 Rate Limit) atingido.",
    "smart_fallback_init": "Iniciando mecanismo de Fallback Inteligente para download...",
    "smart_fallback_link": "Link gerado por Fallback Inteligente: {oc_url}",
    "smart_fallback_error": "Erro crítico: Fallback falhou e a API oficial está bloqueada.",
    "smart_fallback_unsupported_pre": "Erro crítico: Não existe Fallback Inteligente para versões pre-release ao sofrer Rate Limit. Tente mais tarde.",
    "checksum_error_skip": "Não foi possível obter o checksum SHA-256. A verificação será pulada. Erro: {e}",
    "size_not_specified": "Tamanho não especificado pelo servidor, baixando...",
    "download_size_mismatch": "Erro: Tamanho do download não corresponde. Arquivo pode estar corrompido.",
    "checksum_fatal_error": "Erro fatal: O Checksum SHA-256 do arquivo baixado ({downloaded_checksum}) não bate com o esperado ({expected_checksum}). O arquivo pode estar comprometido!",
    "checksum_verified_super": "Checksum SHA-256 verificado com super sucesso.",
    "oc_download_extract_success": "OpenCore versão {build_type} baixado e extraído de forma 100% segura.",
    "chk_version_api_err": "Falha ao checar visão via API (pode ser Rate Limit). Tentando método Fallback Inteligente...",
    "smart_fallback_active": "Fallback Inteligente ativado: Versão {tag} recuperada com sucesso!",
    "smart_fallback_failed": "O Fallback Inteligente também falhou: {fallback_e}",
    "dependencies_check": "Verificando dependências...",
    "dependency_not_found": "Erro: Dependência '{cmd}' não encontrada.",
    "python3_needed": "O Python 3 é necessário para o script. Instale-o através do Homebrew com 'brew install python3'.",
    "dependencies_success": "Todas as dependências estão disponíveis.",
    "invalid_option": "Opção inválida. Tente novamente.",
    "backup_limit_deleted": "Backup antigo removido para manter o limite de rotação: {folder}",
    "y_n_prompt": "(s/n)",
    "safe_delete_prompt": "Você tem ABSOLUTA certeza que deseja remover esses drivers permanentemente? (y/n): ",
    "drivers_kept": "Drivers conservados intactos na EFI.",
    "drivers_unused_removed": "Limpeza efetuada! Os drivers não utilizados foram apagados da EFI."
}

def update_json(file, new_data):
    try:
        with open(file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        for k, v in new_data.items():
            if k not in data or data[k] != v:
                data[k] = v
        with open(file, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
    except Exception as e:
        print(f"Error updating {file}: {e}")

update_json("update_opencore/translations/en.json", new_en)
update_json("update_opencore/translations/pt-BR.json", new_pt)
print("Translations updated.")
